"""Answer Agent: generates a grounded response with citations from the
chunks the Retriever Agent found."""
from app.config import get_settings
from agents.llm_client import get_chat_client
from agents.state import AgentState

SYSTEM_PROMPT = (
    "You are ContextPilot AI, an enterprise knowledge assistant. Answer the "
    "user's question using ONLY the numbered context snippets provided. "
    "Cite sources inline using [1], [2], etc. matching the snippet numbers. "
    "If the context does not contain enough information to answer "
    "confidently, say so explicitly instead of guessing."
)


def _build_user_prompt(question: str, chunks: list[dict]) -> str:
    context_block = "\n\n".join(f"[{i + 1}] {c['content']}" for i, c in enumerate(chunks))
    return f"Context:\n{context_block}\n\nQuestion: {question}\n\nAnswer:"


def _compose_extractive_answer(question: str, chunks: list[dict]) -> str:
    """Deterministic, offline fallback used when no real LLM key is
    configured: composes an answer by stitching the most relevant snippets
    together with citation markers, rather than paraphrasing them."""
    if not chunks:
        return (
            "I couldn't find any relevant information in the knowledge base "
            "to answer this question. Please upload a relevant document or "
            "rephrase your question."
        )

    lines = [f"Based on the retrieved knowledge base context, here is what's available regarding: \"{question}\""]
    for i, chunk in enumerate(chunks):
        snippet = chunk["content"].strip()
        if len(snippet) > 400:
            snippet = snippet[:400].rsplit(" ", 1)[0] + "..."
        lines.append(f"- {snippet} [{i + 1}]")
    lines.append(
        "\n(Generated by the offline extractive fallback — configure a real "
        "OPENAI_API_KEY or ANTHROPIC_API_KEY for fully synthesized answers.)"
    )
    return "\n".join(lines)


def run(state: AgentState) -> AgentState:
    settings = get_settings()
    chunks = state.get("retrieved_chunks", [])
    chat_client = get_chat_client(settings)

    if chat_client is not None:
        content = chat_client.complete(SYSTEM_PROMPT, _build_user_prompt(state["question"], chunks))
    else:
        content = _compose_extractive_answer(state["question"], chunks)

    state["answer_content"] = content
    state["citations"] = [
        {
            "chunk_id": c["chunk_id"],
            "document_id": c["document_id"],
            "snippet": c["content"][:280],
            "similarity": c["similarity"],
            "source": c["source"],
        }
        for c in chunks
    ]
    return state
